export const FETCH_INDIVIDUAL_POST_REQUEST = 'FETCH_INDIVIDUAL_POST_REQUEST';
export const FETCH_INDIVIDUAL_POST_SUCCESS = 'FETCH_INDIVIDUAL_POST_SUCCESS';
export const FETCH_INDIVIDUAL_POST_FAILURE = 'FETCH_INDIVIDUAL_POST_FAILURE';
